#!/usr/bin/env bun
/**
 * Convert WNF JSON files to Markdown for easier review
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, basename } from "node:path";
import type { WNFDocument, Category } from "../../packages/types/src/index.js";

const INPUT_DIR = "./.output/e2e-results";
const OUTPUT_DIR = "./.output/e2e-results";

function toMarkdown(wnf: WNFDocument, filename: string): string {
	const lines: string[] = [];

	// Header
	lines.push(`# ${wnf.source.repo} - ${wnf.version}`);
	lines.push("");

	// Metadata table
	lines.push("## Metadata");
	lines.push("");
	lines.push("| Field | Value |");
	lines.push("|-------|-------|");
	lines.push(`| **Version** | ${wnf.version} |`);
	lines.push(`| **Released** | ${wnf.releasedAt || "N/A"} |`);
	lines.push(`| **Confidence** | ${(wnf.confidence * 100).toFixed(0)}% |`);
	lines.push(`| **Sources** | ${wnf.generatedFrom.join(", ")} |`);
	lines.push(`| **Release URL** | [View on GitHub](${wnf.links.release}) |`);
	lines.push("");

	// Summary
	if (wnf.summary) {
		lines.push("## Summary");
		lines.push("");
		lines.push(wnf.summary);
		lines.push("");
	}

	// Statistics
	const totalItems = wnf.categories.reduce((sum, cat) => sum + cat.items.length, 0);
	lines.push("## Statistics");
	lines.push("");
	lines.push(`- **Total Items**: ${totalItems}`);
	lines.push(`- **Categories**: ${wnf.categories.length}`);
	lines.push("");

	// Categories
	lines.push("## Changes");
	lines.push("");

	for (const category of wnf.categories) {
		lines.push(`### ${category.title} (${category.items.length})`);
		lines.push("");

		for (const item of category.items) {
			const refs = item.refs?.length
				? ` (${item.refs.map((r) => `#${r}`).join(", ")})`
				: "";
			lines.push(`- ${item.text}${refs}`);
		}
		lines.push("");
	}

	// Footer
	lines.push("---");
	lines.push("");
	lines.push(`*Generated by WNF at ${wnf.generatedAt}*`);

	return lines.join("\n");
}

async function main() {
	const files = await readdir(INPUT_DIR);
	const jsonFiles = files.filter((f) => f.endsWith(".json"));

	console.log(`Converting ${jsonFiles.length} JSON files to Markdown...\n`);

	for (const file of jsonFiles) {
		try {
			const jsonPath = join(INPUT_DIR, file);
			const content = await readFile(jsonPath, "utf-8");
			const wnf: WNFDocument = JSON.parse(content);

			const mdFilename = file.replace(".json", ".md");
			const mdPath = join(OUTPUT_DIR, mdFilename);
			const markdown = toMarkdown(wnf, file);

			await writeFile(mdPath, markdown);
			console.log(`✓ ${mdFilename}`);
		} catch (error) {
			console.error(`✗ ${file}: ${error instanceof Error ? error.message : error}`);
		}
	}

	console.log(`\nMarkdown files saved to ${OUTPUT_DIR}/`);
}

main();
