#!/usr/bin/env bun
/**
 * Convert WNF Aggregated JSON files to Markdown for easier review
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, basename } from "node:path";
import type { WNFAggregatedDocument, Category } from "../../packages/types/src/index.js";

const INPUT_DIR = "./.output/e2e-results-since-nov1";
const OUTPUT_DIR = "./.output/e2e-results-since-nov1";

function toMarkdown(wnf: WNFAggregatedDocument, filename: string): string {
	const lines: string[] = [];

	// Header
	lines.push(`# ${wnf.source.repo} - Since ${wnf.source.dateRange.since.split("T")[0]}`);
	lines.push("");

	// Metadata table
	lines.push("## Metadata");
	lines.push("");
	lines.push("| Field | Value |");
	lines.push("|-------|-------|");
	lines.push(`| **Date Range** | ${wnf.source.dateRange.since.split("T")[0]} to ${wnf.source.dateRange.until.split("T")[0]} |`);
	lines.push(`| **Releases** | ${wnf.releaseCount} |`);
	lines.push(`| **Confidence** | ${(wnf.confidence * 100).toFixed(0)}% |`);
	lines.push(`| **Sources** | ${wnf.generatedFrom.join(", ")} |`);
	lines.push("");

	// Summary
	if (wnf.summary) {
		lines.push("## Summary");
		lines.push("");
		lines.push(wnf.summary);
		lines.push("");
	}

	// Releases included
	if (wnf.releases && wnf.releases.length > 0) {
		lines.push("## Releases Included");
		lines.push("");
		for (const release of wnf.releases.slice(0, 20)) { // Show first 20
			lines.push(`- [${release.version}](${release.url}) (${release.releasedAt.split("T")[0]})`);
		}
		if (wnf.releases.length > 20) {
			lines.push(`- ... and ${wnf.releases.length - 20} more`);
		}
		lines.push("");
	}

	// Statistics
	const totalItems = wnf.categories.reduce((sum, cat) => sum + cat.items.length, 0);
	lines.push("## Statistics");
	lines.push("");
	lines.push(`- **Total Items**: ${totalItems}`);
	lines.push(`- **Categories**: ${wnf.categories.length}`);
	lines.push("");

	// Categories
	lines.push("## Changes");
	lines.push("");

	for (const category of wnf.categories) {
		lines.push(`### ${category.title} (${category.items.length})`);
		lines.push("");

		// Show first 30 items per category to keep it readable
		const itemsToShow = category.items.slice(0, 30);
		for (const item of itemsToShow) {
			const refs = item.refs?.length
				? ` (#${item.refs.join(", #")})`
				: "";
			lines.push(`- ${item.text}${refs}`);
		}
		if (category.items.length > 30) {
			lines.push(`- ... and ${category.items.length - 30} more`);
		}
		lines.push("");
	}

	// Footer
	lines.push("---");
	lines.push("");
	lines.push(`*Generated by WNF at ${wnf.generatedAt}*`);

	return lines.join("\n");
}

async function main() {
	const files = await readdir(INPUT_DIR);
	const jsonFiles = files.filter((f) => f.endsWith(".json"));

	console.log(`Converting ${jsonFiles.length} JSON files to Markdown...\n`);

	for (const file of jsonFiles) {
		try {
			const jsonPath = join(INPUT_DIR, file);
			const content = await readFile(jsonPath, "utf-8");
			const wnf: WNFAggregatedDocument = JSON.parse(content);

			const mdFilename = file.replace(".json", ".md");
			const mdPath = join(OUTPUT_DIR, mdFilename);
			const markdown = toMarkdown(wnf, file);

			await writeFile(mdPath, markdown);
			console.log(`✓ ${mdFilename}`);
		} catch (error) {
			console.error(`✗ ${file}: ${error instanceof Error ? error.message : error}`);
		}
	}

	console.log(`\nMarkdown files saved to ${OUTPUT_DIR}/`);
}

main();
